---
- name: Install all necessary packages
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  with_items:
    - unclutter
    - x11-xserver-utils
    - "{{ browser_pkg }}"
    - ttf-mscorefonts-installer
  become: yes
  tags: ['install']

- name: Disable the screensaver in autostart
  replace:
    path: '.config/lxsession/LXDE-pi/autostart'
    regexp: '(^@xscreensaver.*)'
    replace: '# \1'
    #backup: yes
  tags: ['startup']

- name: Append the browser starter script to autostart
  blockinfile:
    path: '.config/lxsession/LXDE-pi/autostart'
    state: present
    block: |
      @/usr/bin/{{ browser_pkg }} --incognito --start-maximized --kiosk {{ kiosk_url }}
      @unclutter # hide mouse cursor
      @xset s off # disable screensaver
      @xset s noblank # disable screen blanking
      @xset -dpms # disable power management signaling
  tags: ['startup']